SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

-- Canonical UOM Archive production seed.
-- Image URLs are synchronized with backend/prisma/seed.ts and release/seed-assets/manifest.json.
-- This removes older seed rows that may still point to .jpg or stale generated assets.
DELETE FROM `_RelatedProducts` WHERE `A` LIKE 'prod-%' OR `B` LIKE 'prod-%';
DELETE FROM `banners` WHERE `id` IN ('banner-home-main','banner-new-collection') OR `imageUrl` LIKE 'https://images.uomarchive.com/seed/%';
DELETE FROM `products` WHERE `id` LIKE 'prod-%' OR `images` LIKE '%https://images.uomarchive.com/seed/%' OR `hoverImage` LIKE 'https://images.uomarchive.com/seed/%';
DELETE FROM `categories` WHERE `id` LIKE 'cat-%' OR `image` LIKE 'https://images.uomarchive.com/seed/%';
DELETE FROM `site_content` WHERE `id` LIKE 'content-%' OR `key` IN (
  'menu.shop.vi','menu.shop.en','menu.inquiry.vi','menu.inquiry.en','menu.shipping.vi','menu.shipping.en',
  'brand.name.vi','brand.name.en','brand.tagline.vi','brand.tagline.en','footer.text.vi','footer.text.en',
  'hero.title.vi','hero.title.en','hero.subtitle.vi','hero.subtitle.en','hero.image.vi','hero.image.en',
  'inquiry.button.vi','inquiry.button.en','site.title.vi','site.title.en','site.description.vi','site.description.en',
  'site.logoUrl','site.loadingText','journal.stories','search.trending.vi','search.trending.en',
  'about.heroTitle.vi','about.heroTitle.en','about.heroSubtitle.vi','about.heroSubtitle.en',
  'about.storyTitle.vi','about.storyTitle.en','about.storyContent.vi','about.storyContent.en','about.storyImage',
  'about.philosophyTitle.vi','about.philosophyTitle.en','about.philosophyDescription.vi','about.philosophyDescription.en',
  'about.philosophyContent.vi','about.philosophyContent.en','about.values.craft.title.vi','about.values.craft.title.en',
  'about.values.craft.description.vi','about.values.craft.description.en','about.values.sustainability.title.vi',
  'about.values.sustainability.title.en','about.values.sustainability.description.vi','about.values.sustainability.description.en',
  'about.values.essence.title.vi','about.values.essence.title.en','about.values.essence.description.vi','about.values.essence.description.en'
);
DELETE FROM `theme_settings` WHERE `id` = 'singleton';
DELETE FROM `social_settings` WHERE `id` = 'singleton';
DELETE FROM `site_settings` WHERE `id` = 'singleton' OR `key` = 'exchange_rate';
DELETE FROM `users` WHERE `id` IN ('manager-seed','admin-seed');

INSERT INTO `users` (`id`,`email`,`passwordHash`,`fullName`,`role`,`isActive`,`createdAt`,`updatedAt`) VALUES
('admin-seed', 'admin@uomarchive.com', '$2b$10$7Kx6Cz4/ngE/GmsyZUZfIurYCEABG9sY674ATCjIjv7I7HmLCuXdi', 'Admin User', 'ADMIN', 1, NOW(3), NOW(3))
ON DUPLICATE KEY UPDATE `passwordHash`=VALUES(`passwordHash`), `fullName`=VALUES(`fullName`), `role`=VALUES(`role`), `isActive`=VALUES(`isActive`), `updatedAt`=NOW(3);

INSERT INTO `users` (`id`,`email`,`passwordHash`,`fullName`,`role`,`isActive`,`createdBy`,`createdAt`,`updatedAt`) VALUES
('manager-seed', 'manager@uomarchive.com', '$2b$10$iTfxvz1z9mlIDmqeehC0XuKa4lVZrS5G0zVDnIuSe4s4T0IIgVbrO', 'Manager User', 'MANAGER', 1, 'admin-seed', NOW(3), NOW(3))
ON DUPLICATE KEY UPDATE `passwordHash`=VALUES(`passwordHash`), `fullName`=VALUES(`fullName`), `role`=VALUES(`role`), `isActive`=VALUES(`isActive`), `updatedBy`='admin-seed', `updatedAt`=NOW(3);

INSERT INTO `theme_settings` (`id`,`backgroundColor`,`textColor`,`accentColor`,`updatedAt`,`updatedBy`) VALUES ('singleton','#F9F7F1','#4A4238','#8C7E6A',NOW(3),'admin-seed') ON DUPLICATE KEY UPDATE `backgroundColor`=VALUES(`backgroundColor`), `textColor`=VALUES(`textColor`), `accentColor`=VALUES(`accentColor`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `social_settings` (`id`,`facebookPageUrl`,`instagramUsername`,`updatedAt`,`updatedBy`) VALUES ('singleton','https://m.me/uomarchive','uomarchive',NOW(3),'admin-seed') ON DUPLICATE KEY UPDATE `facebookPageUrl`=VALUES(`facebookPageUrl`), `instagramUsername`=VALUES(`instagramUsername`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_settings` (`id`,`key`,`value`) VALUES ('singleton','exchange_rate','25000') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-001', 'menu.shop.vi', 'SAN PHAM', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-002', 'menu.shop.en', 'SHOP', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-003', 'menu.inquiry.vi', 'HOI SAN PHAM', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-004', 'menu.inquiry.en', 'INQUIRE', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-005', 'menu.shipping.vi', 'VAN CHUYEN & DOI TRA', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-006', 'menu.shipping.en', 'SHIPPING & RETURNS', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-007', 'brand.name.vi', 'ƯƠM.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-008', 'brand.name.en', 'ƯƠM.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-009', 'brand.tagline.vi', 'Gom su thu cong Viet Nam', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-010', 'brand.tagline.en', 'Handcrafted ceramics from Vietnam', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-011', 'footer.text.vi', '2026 ƯƠM. Tat ca quyen duoc bao luu.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-012', 'footer.text.en', '2026 ƯƠM. All rights reserved.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-013', 'hero.title.vi', 'Ve dep trong su tinh lang', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-014', 'hero.title.en', 'Beauty in Stillness', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-015', 'hero.subtitle.vi', 'Gom su thu cong tu Viet Nam', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-016', 'hero.subtitle.en', 'Handcrafted ceramics from Vietnam', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-017', 'inquiry.button.vi', 'Hoi san pham', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-018', 'inquiry.button.en', 'Inquire', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-019', 'site.title.vi', 'ƯƠM. - Gom su thu cong Viet Nam', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-020', 'site.title.en', 'ƯƠM. - Handcrafted Ceramics from Vietnam', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-021', 'site.description.vi', 'ƯƠM. tuyen chon gom su thu cong Viet Nam, luu giu ve dep moc mac, tinh te va cau chuyen cua nghe nhan ban dia.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-022', 'site.description.en', 'Discover Vietnamese handcrafted ceramics curated for quiet beauty, refined living, and artisan stories.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-023', 'site.logoUrl', '', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-024', 'site.loadingText', 'ƯƠM.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-025', 'hero.image.vi', 'https://images.uomarchive.com/seed/hero.png', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-026', 'hero.image.en', 'https://images.uomarchive.com/seed/hero.png', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-027', 'journal.stories', '[{"id":"story-hands-that-keep-the-fire","slug":"hands-that-keep-the-fire","slugVi":"nhung-ban-tay-giu-lua","slugEn":"hands-that-keep-the-fire","titleVi":"Nhung ban tay giu lua","titleEn":"Hands That Keep the Fire","summaryVi":"Cau chuyen ve nhung nguoi tho gom va nhip song cham trong xuong.","summaryEn":"A story about ceramic artisans and the quiet rhythm of the workshop.","contentVi":"<p>Moi san pham bat dau tu dat, lua va su kien nhan cua ban tay nguoi tho.</p>","contentEn":"<p>Every piece begins with clay, fire, and the patience of the maker.</p>","imageUrl":"https://images.uomarchive.com/seed/journal-hands.png","publishedAt":"2026-03-12","updatedAt":"2026-03-12","isVisible":true},{"id":"story-glaze-and-light","slug":"glaze-and-light","slugVi":"mau-men-va-anh-sang","slugEn":"glaze-and-light","titleVi":"Mau men va anh sang","titleEn":"Glaze and Light","summaryVi":"Cach men gom thay doi tinh te theo tung nguon sang trong nha.","summaryEn":"How ceramic glaze shifts gently with different sources of light.","contentVi":"<p>Men gom co the am hon, sau hon hoac diu hon tuy theo anh sang tu nhien va den trong nha.</p>","contentEn":"<p>Glaze can feel warmer, deeper, or softer depending on daylight and indoor lighting.</p>","imageUrl":"https://images.uomarchive.com/seed/journal-glaze.png","publishedAt":"2026-03-20","updatedAt":"2026-03-20","isVisible":true},{"id":"story-minimal-tea-ritual","slug":"minimal-tea-ritual","slugVi":"nghi-thuc-ban-tra-toi-gian","slugEn":"minimal-tea-ritual","titleVi":"Nghi thuc ban tra toi gian","titleEn":"A Minimal Tea Ritual","summaryVi":"Mot vai mon gom vua du de tao nen khoang lang yen trong ngay.","summaryEn":"A few thoughtful ceramic pieces can create a calm daily pause.","contentVi":"<p>Mot am tra, vai chiec chen va mot khoang trong la du cho mot nghi thuc nho.</p>","contentEn":"<p>A teapot, a few cups, and some empty space are enough for a small ritual.</p>","imageUrl":"https://images.uomarchive.com/seed/journal-tea.png","publishedAt":"2026-03-28","updatedAt":"2026-03-28","isVisible":true}]', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-028', 'search.trending.vi', '["binh gom","chen tra","men ran","bo suu tap moi","lo hoa toi gian"]', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-029', 'search.trending.en', '["ceramic vase","tea cup","crackle glaze","new collection","minimal decor"]', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-030', 'about.heroTitle.vi', 'VE ƯƠM. ARCHIVE', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-031', 'about.heroTitle.en', 'ABOUT ƯƠM. ARCHIVE', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-032', 'about.heroSubtitle.vi', 'Noi luu giu ve dep tinh lang cua gom su thu cong Viet Nam.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-033', 'about.heroSubtitle.en', 'A quiet archive of Vietnamese handcrafted ceramics.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-034', 'about.storyTitle.vi', 'Cau chuyen cua chung toi', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-035', 'about.storyTitle.en', 'Our Story', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-036', 'about.storyContent.vi', 'ƯƠM. Archive duoc tao nen tu niem yeu thich voi chat lieu dat, men va nhung dau vet thu cong. Chung toi tuyen chon nhung vat pham co tinh ung dung, song cham va ben lau trong khong gian song hien dai.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-037', 'about.storyContent.en', 'ƯƠM. Archive is built from a love for clay, glaze, and handmade traces. We curate practical objects that invite slower, quieter living.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-038', 'about.storyImage', 'https://images.uomarchive.com/seed/about-story.png', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-039', 'about.philosophyTitle.vi', 'Triet ly thiet ke', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-040', 'about.philosophyTitle.en', 'Design Philosophy', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-041', 'about.philosophyDescription.vi', 'Toi gian, chan that, ben vung.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-042', 'about.philosophyDescription.en', 'Minimal, honest, enduring.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-043', 'about.philosophyContent.vi', 'Chung toi tin rang ve dep nam trong ti le vua du, be mat co cam xuc va kha nang dong hanh cung doi song hang ngay.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-044', 'about.philosophyContent.en', 'We believe beauty lives in balanced proportion, tactile surfaces, and objects that stay close to everyday life.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-045', 'about.values.craft.title.vi', 'Thu cong', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-046', 'about.values.craft.title.en', 'Craft', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-047', 'about.values.craft.description.vi', 'Moi san pham duoc chon loc voi su ton trong ban tay nguoi tho.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-048', 'about.values.craft.description.en', 'Each piece is selected with respect for the maker behind it.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-049', 'about.values.sustainability.title.vi', 'Ben vung', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-050', 'about.values.sustainability.title.en', 'Sustainability', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-051', 'about.values.sustainability.description.vi', 'Uu tien chat lieu lau ben va cach su dung co trach nhiem.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-052', 'about.values.sustainability.description.en', 'We favor lasting materials and responsible everyday use.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-053', 'about.values.essence.title.vi', 'Tinh te', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-054', 'about.values.essence.title.en', 'Essence', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-055', 'about.values.essence.description.vi', 'Giu lai nhung gi can thiet, loai bo su on ao thua.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `site_content` (`id`,`key`,`value`,`updatedAt`,`updatedBy`) VALUES ('content-056', 'about.values.essence.description.en', 'Keep what matters, remove unnecessary noise.', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';

INSERT INTO `categories` (`id`,`slug`,`nameVi`,`nameEn`,`descriptionVi`,`descriptionEn`,`image`,`order`,`isActive`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('cat-binh-hoa-loc', 'binh-hoa-loc', 'Binh hoa & Lo', 'Vases & Jars', 'Binh gom thu cong danh cho trang tri khong gian song va cam hoa.', 'Handcrafted ceramic vases for floral styling and interior display.', 'https://images.uomarchive.com/seed/cat-vases.png', 1, 1, NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `image`=VALUES(`image`), `order`=VALUES(`order`), `isActive`=VALUES(`isActive`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `categories` (`id`,`slug`,`nameVi`,`nameEn`,`descriptionVi`,`descriptionEn`,`image`,`order`,`isActive`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('cat-bo-ban-an', 'bo-ban-an', 'Bo ban an', 'Dinnerware Sets', 'Bo chen dia va phu kien ban an mang tinh than thu cong toi gian.', 'Dinnerware collections crafted for everyday rituals and minimal tables.', 'https://images.uomarchive.com/seed/cat-dinnerware.png', 2, 1, NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `image`=VALUES(`image`), `order`=VALUES(`order`), `isActive`=VALUES(`isActive`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `categories` (`id`,`slug`,`nameVi`,`nameEn`,`descriptionVi`,`descriptionEn`,`image`,`order`,`isActive`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('cat-chen-coc-tra', 'chen-coc-tra', 'Chen & Coc tra', 'Tea Cups', 'Chen coc gom cam tay vua van, men moc, phu hop dung hang ngay.', 'Tactile handcrafted cups made for daily tea rituals.', 'https://images.uomarchive.com/seed/cat-tea.png', 3, 1, NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `image`=VALUES(`image`), `order`=VALUES(`order`), `isActive`=VALUES(`isActive`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `categories` (`id`,`slug`,`nameVi`,`nameEn`,`descriptionVi`,`descriptionEn`,`image`,`order`,`isActive`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('cat-dia-khay', 'dia-khay', 'Dia & Khay', 'Plates & Trays', 'Dia gom men ran va khay phuc vu co do hoan thien cao.', 'Glazed ceramic plates and trays with balanced handcrafted finishes.', 'https://images.uomarchive.com/seed/cat-trays.png', 4, 1, NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `image`=VALUES(`image`), `order`=VALUES(`order`), `isActive`=VALUES(`isActive`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';

INSERT INTO `products` (`id`,`slug`,`nameVi`,`nameEn`,`shortDescriptionVi`,`shortDescriptionEn`,`descriptionVi`,`descriptionEn`,`categoryId`,`priceVND`,`priceUSD`,`salePriceVND`,`salePriceUSD`,`images`,`hoverImage`,`material`,`dimensions`,`stock`,`isActive`,`isFeatured`,`inquiryEnabled`,`inquiryMessageVi`,`inquiryMessageEn`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('prod-binh-gom-trang-lieng', 'binh-gom-trang-lieng', 'Binh Gom Lieng Men Nga', 'Lieng Ivory Ceramic Vase', 'Binh gom dang cao, men nga mo toi gian.', 'A tall ceramic vase with minimalist matte ivory glaze.', '<p>Binh gom Lieng mang ve dep tinh lang cho khong gian song.</p>', '<p>The Lieng vase brings a quiet handmade presence to any room.</p>', 'cat-binh-hoa-loc', 1850000, 74.0, 1690000, 67.6, '["https://images.uomarchive.com/seed/product-vase-1.png","https://images.uomarchive.com/seed/product-vase-2.png"]', 'https://images.uomarchive.com/seed/product-vase-2.png', 'High-fire white clay', '18cm x 45cm', 5, 1, 1, 1, 'Toi quan tam den san pham Binh Gom Lieng Men Nga.', 'I am interested in Lieng Ivory Ceramic Vase.', NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `shortDescriptionVi`=VALUES(`shortDescriptionVi`), `shortDescriptionEn`=VALUES(`shortDescriptionEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `categoryId`=VALUES(`categoryId`), `priceVND`=VALUES(`priceVND`), `priceUSD`=VALUES(`priceUSD`), `salePriceVND`=VALUES(`salePriceVND`), `salePriceUSD`=VALUES(`salePriceUSD`), `images`=VALUES(`images`), `hoverImage`=VALUES(`hoverImage`), `material`=VALUES(`material`), `dimensions`=VALUES(`dimensions`), `stock`=VALUES(`stock`), `isActive`=VALUES(`isActive`), `isFeatured`=VALUES(`isFeatured`), `inquiryEnabled`=VALUES(`inquiryEnabled`), `inquiryMessageVi`=VALUES(`inquiryMessageVi`), `inquiryMessageEn`=VALUES(`inquiryMessageEn`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `products` (`id`,`slug`,`nameVi`,`nameEn`,`shortDescriptionVi`,`shortDescriptionEn`,`descriptionVi`,`descriptionEn`,`categoryId`,`priceVND`,`priceUSD`,`salePriceVND`,`salePriceUSD`,`images`,`hoverImage`,`material`,`dimensions`,`stock`,`isActive`,`isFeatured`,`inquiryEnabled`,`inquiryMessageVi`,`inquiryMessageEn`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('prod-binh-hoa-abstract', 'binh-hoa-abstract', 'Binh Hoa Gom Abstract', 'Abstract Sculptural Ceramic Vase', 'Binh hoa nghe thuat voi duong net bat doi xung.', 'Artistic vase with asymmetric sculptural lines.', '<p>Mot diem nhan nghe thuat cho ke sach, ban console hoac phong khach.</p>', '<p>A sculptural accent for shelves, consoles, and living rooms.</p>', 'cat-binh-hoa-loc', 2100000, 84.0, NULL, NULL, '["https://images.uomarchive.com/seed/product-vase-3.png","https://images.uomarchive.com/seed/product-vase-4.png"]', 'https://images.uomarchive.com/seed/product-vase-4.png', 'Raw kaolin clay', '30cm x 18cm', 4, 1, 1, 1, 'Toi quan tam den san pham Binh Hoa Gom Abstract.', 'I am interested in Abstract Sculptural Ceramic Vase.', NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `shortDescriptionVi`=VALUES(`shortDescriptionVi`), `shortDescriptionEn`=VALUES(`shortDescriptionEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `categoryId`=VALUES(`categoryId`), `priceVND`=VALUES(`priceVND`), `priceUSD`=VALUES(`priceUSD`), `salePriceVND`=VALUES(`salePriceVND`), `salePriceUSD`=VALUES(`salePriceUSD`), `images`=VALUES(`images`), `hoverImage`=VALUES(`hoverImage`), `material`=VALUES(`material`), `dimensions`=VALUES(`dimensions`), `stock`=VALUES(`stock`), `isActive`=VALUES(`isActive`), `isFeatured`=VALUES(`isFeatured`), `inquiryEnabled`=VALUES(`inquiryEnabled`), `inquiryMessageVi`=VALUES(`inquiryMessageVi`), `inquiryMessageEn`=VALUES(`inquiryMessageEn`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `products` (`id`,`slug`,`nameVi`,`nameEn`,`shortDescriptionVi`,`shortDescriptionEn`,`descriptionVi`,`descriptionEn`,`categoryId`,`priceVND`,`priceUSD`,`salePriceVND`,`salePriceUSD`,`images`,`hoverImage`,`material`,`dimensions`,`stock`,`isActive`,`isFeatured`,`inquiryEnabled`,`inquiryMessageVi`,`inquiryMessageEn`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('prod-bo-chen-dia-moc', 'bo-chen-dia-moc', 'Bo Chen Dia Gom Moc', 'Moc Dinnerware Set', 'Bo ban an gom moc cho bua com hang ngay.', 'Rustic dinnerware set for daily rituals.', '<p>Bo san pham mang lai cam giac am ap va moc mac tren ban an.</p>', '<p>A warm and rustic dinnerware set for the everyday table.</p>', 'cat-bo-ban-an', 3200000, 128.0, 2890000, 115.6, '["https://images.uomarchive.com/seed/product-dinner-1.png","https://images.uomarchive.com/seed/product-dinner-2.png"]', 'https://images.uomarchive.com/seed/product-dinner-2.png', 'Stoneware', 'Assorted sizes', 3, 1, 1, 1, 'Toi quan tam den san pham Bo Chen Dia Gom Moc.', 'I am interested in Moc Dinnerware Set.', NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `shortDescriptionVi`=VALUES(`shortDescriptionVi`), `shortDescriptionEn`=VALUES(`shortDescriptionEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `categoryId`=VALUES(`categoryId`), `priceVND`=VALUES(`priceVND`), `priceUSD`=VALUES(`priceUSD`), `salePriceVND`=VALUES(`salePriceVND`), `salePriceUSD`=VALUES(`salePriceUSD`), `images`=VALUES(`images`), `hoverImage`=VALUES(`hoverImage`), `material`=VALUES(`material`), `dimensions`=VALUES(`dimensions`), `stock`=VALUES(`stock`), `isActive`=VALUES(`isActive`), `isFeatured`=VALUES(`isFeatured`), `inquiryEnabled`=VALUES(`inquiryEnabled`), `inquiryMessageVi`=VALUES(`inquiryMessageVi`), `inquiryMessageEn`=VALUES(`inquiryMessageEn`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `products` (`id`,`slug`,`nameVi`,`nameEn`,`shortDescriptionVi`,`shortDescriptionEn`,`descriptionVi`,`descriptionEn`,`categoryId`,`priceVND`,`priceUSD`,`salePriceVND`,`salePriceUSD`,`images`,`hoverImage`,`material`,`dimensions`,`stock`,`isActive`,`isFeatured`,`inquiryEnabled`,`inquiryMessageVi`,`inquiryMessageEn`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('prod-coc-uong-tra-nham', 'coc-uong-tra-nham', 'Coc Tra Gom Men Nham', 'Matte Handleless Tea Cup', 'Coc tra nho gon, men nham moc mac.', 'Compact handleless tea cup with rustic matte glaze.', '<p>Thich hop cho thoi quen uong tra cham vao buoi sang.</p>', '<p>Perfect for slow morning tea and quiet pauses.</p>', 'cat-chen-coc-tra', 250000, 10.0, NULL, NULL, '["https://images.uomarchive.com/seed/product-tea-1.png","https://images.uomarchive.com/seed/product-tea-2.png"]', 'https://images.uomarchive.com/seed/product-tea-2.png', 'Matte glazed ceramic', '8cm x 6cm', 50, 1, 0, 1, 'Toi quan tam den san pham Coc Tra Gom Men Nham.', 'I am interested in Matte Handleless Tea Cup.', NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `shortDescriptionVi`=VALUES(`shortDescriptionVi`), `shortDescriptionEn`=VALUES(`shortDescriptionEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `categoryId`=VALUES(`categoryId`), `priceVND`=VALUES(`priceVND`), `priceUSD`=VALUES(`priceUSD`), `salePriceVND`=VALUES(`salePriceVND`), `salePriceUSD`=VALUES(`salePriceUSD`), `images`=VALUES(`images`), `hoverImage`=VALUES(`hoverImage`), `material`=VALUES(`material`), `dimensions`=VALUES(`dimensions`), `stock`=VALUES(`stock`), `isActive`=VALUES(`isActive`), `isFeatured`=VALUES(`isFeatured`), `inquiryEnabled`=VALUES(`inquiryEnabled`), `inquiryMessageVi`=VALUES(`inquiryMessageVi`), `inquiryMessageEn`=VALUES(`inquiryMessageEn`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `products` (`id`,`slug`,`nameVi`,`nameEn`,`shortDescriptionVi`,`shortDescriptionEn`,`descriptionVi`,`descriptionEn`,`categoryId`,`priceVND`,`priceUSD`,`salePriceVND`,`salePriceUSD`,`images`,`hoverImage`,`material`,`dimensions`,`stock`,`isActive`,`isFeatured`,`inquiryEnabled`,`inquiryMessageVi`,`inquiryMessageEn`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('prod-dia-gom-men-ran', 'dia-gom-men-ran', 'Dia Gom Men Ran', 'Crackle Glaze Plate', 'Dia gom trang tri va phuc vu voi men ran.', 'Serving plate with classic crackle glaze.', '<p>Phu hop bay mon, decor ke bep hoac ban tra.</p>', '<p>Works beautifully for serving or quiet shelf styling.</p>', 'cat-dia-khay', 550000, 22.0, NULL, NULL, '["https://images.uomarchive.com/seed/product-plate-1.png","https://images.uomarchive.com/seed/product-plate-2.png"]', 'https://images.uomarchive.com/seed/product-plate-2.png', 'Premium crackle glaze ceramic', '26cm diameter', 18, 1, 0, 1, 'Toi quan tam den san pham Dia Gom Men Ran.', 'I am interested in Crackle Glaze Plate.', NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `shortDescriptionVi`=VALUES(`shortDescriptionVi`), `shortDescriptionEn`=VALUES(`shortDescriptionEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `categoryId`=VALUES(`categoryId`), `priceVND`=VALUES(`priceVND`), `priceUSD`=VALUES(`priceUSD`), `salePriceVND`=VALUES(`salePriceVND`), `salePriceUSD`=VALUES(`salePriceUSD`), `images`=VALUES(`images`), `hoverImage`=VALUES(`hoverImage`), `material`=VALUES(`material`), `dimensions`=VALUES(`dimensions`), `stock`=VALUES(`stock`), `isActive`=VALUES(`isActive`), `isFeatured`=VALUES(`isFeatured`), `inquiryEnabled`=VALUES(`inquiryEnabled`), `inquiryMessageVi`=VALUES(`inquiryMessageVi`), `inquiryMessageEn`=VALUES(`inquiryMessageEn`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `products` (`id`,`slug`,`nameVi`,`nameEn`,`shortDescriptionVi`,`shortDescriptionEn`,`descriptionVi`,`descriptionEn`,`categoryId`,`priceVND`,`priceUSD`,`salePriceVND`,`salePriceUSD`,`images`,`hoverImage`,`material`,`dimensions`,`stock`,`isActive`,`isFeatured`,`inquiryEnabled`,`inquiryMessageVi`,`inquiryMessageEn`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('prod-khay-tra-go-gom', 'khay-tra-go-gom', 'Khay Tra Gom Vien Go', 'Ceramic Tea Tray with Wood Rim', 'Khay tra ket hop gom moc va go tu nhien.', 'Tea tray blending ceramic and natural wood.', '<p>Khay phuc vu toi gian cho ban tra va goc tiep khach.</p>', '<p>A minimal serving tray for tea tables and quiet hosting.</p>', 'cat-dia-khay', 850000, 34.0, NULL, NULL, '["https://images.uomarchive.com/seed/product-tray-1.png","https://images.uomarchive.com/seed/product-tray-2.png"]', 'https://images.uomarchive.com/seed/product-tray-2.png', 'Raw ceramic and wood', '35cm x 20cm x 3cm', 10, 1, 0, 1, 'Toi quan tam den san pham Khay Tra Gom Vien Go.', 'I am interested in Ceramic Tea Tray with Wood Rim.', NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `shortDescriptionVi`=VALUES(`shortDescriptionVi`), `shortDescriptionEn`=VALUES(`shortDescriptionEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `categoryId`=VALUES(`categoryId`), `priceVND`=VALUES(`priceVND`), `priceUSD`=VALUES(`priceUSD`), `salePriceVND`=VALUES(`salePriceVND`), `salePriceUSD`=VALUES(`salePriceUSD`), `images`=VALUES(`images`), `hoverImage`=VALUES(`hoverImage`), `material`=VALUES(`material`), `dimensions`=VALUES(`dimensions`), `stock`=VALUES(`stock`), `isActive`=VALUES(`isActive`), `isFeatured`=VALUES(`isFeatured`), `inquiryEnabled`=VALUES(`inquiryEnabled`), `inquiryMessageVi`=VALUES(`inquiryMessageVi`), `inquiryMessageEn`=VALUES(`inquiryMessageEn`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `products` (`id`,`slug`,`nameVi`,`nameEn`,`shortDescriptionVi`,`shortDescriptionEn`,`descriptionVi`,`descriptionEn`,`categoryId`,`priceVND`,`priceUSD`,`salePriceVND`,`salePriceUSD`,`images`,`hoverImage`,`material`,`dimensions`,`stock`,`isActive`,`isFeatured`,`inquiryEnabled`,`inquiryMessageVi`,`inquiryMessageEn`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('prod-bo-am-tra-thien', 'bo-am-tra-thien', 'Bo Am Tra Thien', 'Thien Ash Glaze Teapot Set', 'Bo am tra toi gian voi men tro tu nhien.', 'Minimal teapot set with natural ash glaze.', '<p>Set am va chen cho nhung buoi tra cham.</p>', '<p>A teapot and cups set for slow tea moments.</p>', 'cat-chen-coc-tra', 1550000, 62.0, NULL, NULL, '["https://images.uomarchive.com/seed/product-teapot-1.png","https://images.uomarchive.com/seed/product-teapot-2.png"]', 'https://images.uomarchive.com/seed/product-teapot-2.png', 'Ash-glazed stoneware', 'Teapot 350ml, cups 50ml', 8, 1, 1, 1, 'Toi quan tam den san pham Bo Am Tra Thien.', 'I am interested in Thien Ash Glaze Teapot Set.', NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `shortDescriptionVi`=VALUES(`shortDescriptionVi`), `shortDescriptionEn`=VALUES(`shortDescriptionEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `categoryId`=VALUES(`categoryId`), `priceVND`=VALUES(`priceVND`), `priceUSD`=VALUES(`priceUSD`), `salePriceVND`=VALUES(`salePriceVND`), `salePriceUSD`=VALUES(`salePriceUSD`), `images`=VALUES(`images`), `hoverImage`=VALUES(`hoverImage`), `material`=VALUES(`material`), `dimensions`=VALUES(`dimensions`), `stock`=VALUES(`stock`), `isActive`=VALUES(`isActive`), `isFeatured`=VALUES(`isFeatured`), `inquiryEnabled`=VALUES(`inquiryEnabled`), `inquiryMessageVi`=VALUES(`inquiryMessageVi`), `inquiryMessageEn`=VALUES(`inquiryMessageEn`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `products` (`id`,`slug`,`nameVi`,`nameEn`,`shortDescriptionVi`,`shortDescriptionEn`,`descriptionVi`,`descriptionEn`,`categoryId`,`priceVND`,`priceUSD`,`salePriceVND`,`salePriceUSD`,`images`,`hoverImage`,`material`,`dimensions`,`stock`,`isActive`,`isFeatured`,`inquiryEnabled`,`inquiryMessageVi`,`inquiryMessageEn`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('prod-bo-bat-dia-hoa-bien', 'bo-bat-dia-hoa-bien', 'Bo Bat Dia Men Hoa Bien', 'Reactive Glaze Dinnerware Set', 'Bo bat dia cao cap voi hieu ung men hoa bien.', 'Dinnerware set with reactive glaze finish.', '<p>Moi mon co sac men rieng, phu hop lam qua tang tan gia.</p>', '<p>Each piece has its own glaze movement, suitable for gifting or gatherings.</p>', 'cat-bo-ban-an', 4500000, 180.0, NULL, NULL, '["https://images.uomarchive.com/seed/product-dinner-3.png","https://images.uomarchive.com/seed/product-dinner-4.png"]', 'https://images.uomarchive.com/seed/product-dinner-4.png', 'Premium porcelain', '10-piece set', 15, 1, 0, 1, 'Toi quan tam den san pham Bo Bat Dia Men Hoa Bien.', 'I am interested in Reactive Glaze Dinnerware Set.', NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `nameVi`=VALUES(`nameVi`), `nameEn`=VALUES(`nameEn`), `shortDescriptionVi`=VALUES(`shortDescriptionVi`), `shortDescriptionEn`=VALUES(`shortDescriptionEn`), `descriptionVi`=VALUES(`descriptionVi`), `descriptionEn`=VALUES(`descriptionEn`), `categoryId`=VALUES(`categoryId`), `priceVND`=VALUES(`priceVND`), `priceUSD`=VALUES(`priceUSD`), `salePriceVND`=VALUES(`salePriceVND`), `salePriceUSD`=VALUES(`salePriceUSD`), `images`=VALUES(`images`), `hoverImage`=VALUES(`hoverImage`), `material`=VALUES(`material`), `dimensions`=VALUES(`dimensions`), `stock`=VALUES(`stock`), `isActive`=VALUES(`isActive`), `isFeatured`=VALUES(`isFeatured`), `inquiryEnabled`=VALUES(`inquiryEnabled`), `inquiryMessageVi`=VALUES(`inquiryMessageVi`), `inquiryMessageEn`=VALUES(`inquiryMessageEn`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';

INSERT IGNORE INTO `_RelatedProducts` (`A`,`B`) VALUES ('prod-binh-gom-trang-lieng','prod-binh-hoa-abstract'), ('prod-bo-chen-dia-moc','prod-bo-bat-dia-hoa-bien');

INSERT INTO `banners` (`id`,`titleVi`,`titleEn`,`subtitleVi`,`subtitleEn`,`descriptionVi`,`descriptionEn`,`imageUrl`,`mobileImageUrl`,`link`,`order`,`isActive`,`textColor`,`textPosition`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('banner-home-main', 'Ve dep trong su tinh lang', 'Beauty in Stillness', 'Gom su thu cong tu Viet Nam', 'Handcrafted ceramics from Vietnam', '', '', 'https://images.uomarchive.com/seed/banner-main.png', NULL, '/shop', 1, 1, '#FFFFFF', 'center', NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `titleVi`=VALUES(`titleVi`), `titleEn`=VALUES(`titleEn`), `subtitleVi`=VALUES(`subtitleVi`), `subtitleEn`=VALUES(`subtitleEn`), `imageUrl`=VALUES(`imageUrl`), `link`=VALUES(`link`), `order`=VALUES(`order`), `isActive`=VALUES(`isActive`), `textColor`=VALUES(`textColor`), `textPosition`=VALUES(`textPosition`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';
INSERT INTO `banners` (`id`,`titleVi`,`titleEn`,`subtitleVi`,`subtitleEn`,`descriptionVi`,`descriptionEn`,`imageUrl`,`mobileImageUrl`,`link`,`order`,`isActive`,`textColor`,`textPosition`,`createdAt`,`createdBy`,`updatedAt`,`updatedBy`) VALUES ('banner-new-collection', 'Bo suu tap moi', 'New Collection', 'Kham pha nhung mau thiet ke doc dao', 'Discover unique designs', '', '', 'https://images.uomarchive.com/seed/banner-collection.png', NULL, '/shop?sort=newest', 2, 1, '#FFFFFF', 'left', NOW(3), 'admin-seed', NOW(3), 'admin-seed') ON DUPLICATE KEY UPDATE `titleVi`=VALUES(`titleVi`), `titleEn`=VALUES(`titleEn`), `subtitleVi`=VALUES(`subtitleVi`), `subtitleEn`=VALUES(`subtitleEn`), `imageUrl`=VALUES(`imageUrl`), `link`=VALUES(`link`), `order`=VALUES(`order`), `isActive`=VALUES(`isActive`), `textColor`=VALUES(`textColor`), `textPosition`=VALUES(`textPosition`), `updatedAt`=NOW(3), `updatedBy`='admin-seed';

SET FOREIGN_KEY_CHECKS=1;
